ccflags-y += -DDEBUG

obj-$(CONFIG_TOUCHSCREEN_GOODIX_GT738X) += gt738x_ts.o
gt738x_ts-y := goodix_cfg_bin.o goodix_ts_core.o goodix_ts_gesture.o goodix_ts_tools.o goodix_gt738x_update.o goodix_ts_i2c.o

