# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_SPRD) += ud710-3h10u.dtb
dtbo-$(CONFIG_ARCH_SPRD) += ud710-3h10u-overlay.dtbo

always		:= $(dtb-y) $(dtbo-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
