ccflags-y += -I$(srctree)/drivers/soc/sprd/camera/flash/sc2703s/../flash_drv
ccflags-y += -I$(srctree)/drivers/soc/sprd/camera/flash/sc2703s/../../interface

obj-$(CONFIG_SPRD_CAMERA_FLASH_SENSOR_IC) += flash_ic_sc2703.o
flash_ic_sc2703-y := sc2703s_drv.o
